### ISSUE TITLE
State Districts looks like it's working, but it's not

### ISSUE THREAD

**Issue by jimcrist** [josephlacey/com.jlacey.electoral#15]
My database has 13,341 records, mostly in WI.  I'm trying to add state districts.  I've been doing 100 per hour.  Google API says I've made 12,000+ requests and this number goes up 100 every hour.  I thought it would be done by now, so I used search builder to look at the district field, but only 678 records have district numbers.  12,663 do not.  I know there are some bad addresses in there, but my record has a perfectly good address and hasn't been updated yet. It's set for Primary addresses in Wisconsin. The job settings are: level=administrativeArea1, limit=100, update=0.  The scheduled job says "Success (100 addresses districted.)" every time.  I searched for error codes and found 102 records with #403 AccessNotConfigured, which is probably from the beginning, before I got the Google API settings right.  I'm using the current versions of CiviCRM and WordPress.  Please help...thanks!

**Comment by josephlacey** [comment]
Hi Jim,

Are any districts added with each run?  Remember you can manually trigger the scheduled job, so you don't have to wait for the automated run to get a before and after count.

In my early testing this would happen when addresses would result in lookup errors and continually be included in the lookup because they still had no districts.  This is why I added the error codes; the lookup should exclude the address if it's got an error attached to it.

To find where the issue is, you'll need to do some debugging.  There's [a line in the api file](https://github.com/josephlacey/com.jlacey.electoral/blob/master/api/v3/GoogleCivicInformation.php#L374) that you can uncomment to get the SQL query that's selecting the addresses.

`CRM_Core_Error::debug_var('addressSql', $addressSql);`

You can get the output of that debug statement in your log file, and then run that query directly in the database to see what addresses are being selected each run.  Then you can take the parts of the addresses that are returned and run a direct Google API request in your browser. 

https://www.googleapis.com/civicinfo/v2/representatives?levels=$level&roles=legislatorUpperBody&roles=legislatorLowerBody&key=$apikey&address=$streetAddress%20$city%20$stateProvinceAbbrev

Notice that all the $_GET variable values have a `$` and need to be replaced with their respective values, and the address variable has a few subparts.  You can skip some of this work if you want to output [the curl URL for the Google API request](https://github.com/josephlacey/com.jlacey.electoral/blob/master/api/v3/GoogleCivicInformation.php#L127), but this will return all 100 URL lookups and be little harder discern which contact the address is associated with.

I hope this helps you get to the bottom of your issue.

Joseph

**Comment by jimcrist** [comment]
Most of the contacts have districts now, but 1767 records have an error code 403 userRateLimitExceeded.   Why won't it add districts for those records???  I tried doing a profile for the error code, message and reason fields, so I could do a batch update and clear those fields, but I get a "DB Error: no such field" when I try to use that profile,  Ugh...please help!

**Comment by josephlacey** [comment]
Hi Jim,

It looks like you went over your daily rate limit, and Google returned as much.  The extension then processed those as standard error codes.  Clearing those should get them back in the processing queue.

To fix that profile DB error message, I would check the fields included in the profile to make sure there aren't any legacy ones.  You could also turn on debugging and get more information about which field it's complaining about.

I hope this helps.

Joseph

**Comment by jimcrist** [comment]
Hi Joseph,
I don't think this thread should be closed.  It's doing 24,000 lookups per day and it's not making any progress at all.  I can select at least 822 records that it never gets to.  No error code.  Good addresses. No district records.  Can I pay you to make this more efficient?

**Comment by josephlacey** [comment]
Hey Jim,

As far as you've reported, this issue seems like a data set issue.  I'll reopen it if you can point me to an inefficiency with the code itself.  And yeah, those debugging tips should help you get to the bottom of the issue.

Joseph

**Comment by jimcrist** [comment]
I think I see something.  As I look closely at the 820+ records that ought to get districted, if I take the address and google it, most of them are not perfect.  I have to change the word Apt to #, change Hwy to County, add a space, take out a space, etc.  That seems to be helping.  Why weren't these marked with error code 400 parseError?  Another small complaint, It's always says it districted 1000 addresses, even tho it only did a dozen new ones?!

**Comment by josephlacey** [comment]
Hey Jim, you might want to check out the two latest PR's that came in, #16 and #17.  The latter includes the former, so if you want to apply these patches, you only need to do #17.  Again without more information, I can't say for sure this is the issue you're having, but maybe it'll help.
